#!/usr/bin/env php
<?php

require 'vendor/autoload.php';

use Symfony\Component\Yaml\Yaml;

$yaml = Yaml::parse(file_get_contents('Financial.yaml'));

$app = new Symfony\Component\Console\Application('Financial', '0.0.0');

$app->add(new Financial\InitCommand);

$app->run();
