#!/usr/bin/env php
<?php

require 'vendor/autoload.php';

use Financial\Commands;

$app = new Symfony\Component\Console\Application('Financial', '2.0.0');

$app->add(new Commands\InitCommand);
$app->add(new Commands\OutlookCommand);

$app->run();
